language: cpp

 compiler: gcc

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt5-default qttools-dev-tools sqlite3

 before_script:
   - mkdir build
   - cd build
   - cmake ..

 script: make

 notifications:
   email:
     - joejoshw@gmail.com
     - joshua@megvel.me.ke
   irc:
      channels:
        - "chat.freenode.net#freepayrollke"
      template:
        - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
   on_success: change
   on_failure: always
