language: cpp
compiler:
 - gcc
before_install:
 # rm the rabbitmq source file since it currently times out and we don't need it
 - "sudo rm -f /etc/apt/sources.list.d/rabbitmq-source.list"
 - "sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test"
 - "sudo add-apt-repository -y ppa:kalakris/cmake"
 - "sudo apt-get update -qq"
 - "sudo apt-get install -y g++-4.8"
 - "sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8"
 - "sudo apt-get install -qq wget make ant curl cmake"
 - "sudo apt-get install -qq libegl1-mesa-dev libegl1-mesa"
 - "mkdir qt5"
 - "wget -q -O qt5.zip http://ftp.osuosl.org/pub/musescore/utils/qt542.zip"
 - "unzip -qq qt5.zip -d qt5"
 - "export PATH=`pwd`/qt5/bin:$PATH"
 - "export QT_PLUGIN_PATH=`pwd`/qt5/plugins"
 - bash -c "cmake --version"
script:
 - mkdir build
 - cd build
 #- export CMAKE_PREFIX_PATH=/opt/qt52/lib/cmake
 - cmake ..
 - make
notifications:
 recepients:
  - joejoshw@gmail.com
  - joshua@megvel.me.ke
 email:
  on_success: always
  on_failure: change
 irc:
  channels:
   - "irc.freenode.net#freepayrollke"
  on_success: always
  on_failure: always
