language: cpp
compiler:
 - gcc
env:
 - CONFIG=debug RAGEL=OFF
 - CONFIG=debug RAGEL=ON
 - CONFIG=debug ZLIB=OFF
 - CONFIG=debug QT5=qt5
 - CONFIG=release
 - CONFIG=release QT5=qt5
before_install:
 - sudo apt-add-repository -y ppa:beineri/opt-qt521
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt52base qt52webkit qt52tools
 - bash -c "cmake --version"
script:
 - mkdir build
 - cd build
 - export CMAKE_PREFIX_PATH=/opt/qt52/lib/cmake
 - cmake ..
 - make
notifications:
 recepients:
  - joejoshw@gmail.com
  - joshua@megvel.me.ke
 email:
  on_success: always
  on_failure: change
 irc:
  channels:
   - "irc.freenode.net#freepayrollke"
  on_success: always
  on_failure: always
